// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQGZ_7NQCYlBOIyDsSnWqEqrkn2j0Ebv4',
    appId: '1:1081103792148:web:847ad68fe173aa3e35cf01',
    messagingSenderId: '1081103792148',
    projectId: 'kipas-otomatis-7d7da',
    authDomain: 'kipas-otomatis-7d7da.firebaseapp.com',
    databaseURL: 'https://kipas-otomatis-7d7da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kipas-otomatis-7d7da.firebasestorage.app',
    measurementId: 'G-W8GXWZQC2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNdhoISENe5RLeahW5I5-3XSlX66LOFt4',
    appId: '1:1081103792148:android:41cbb4740fd2d63935cf01',
    messagingSenderId: '1081103792148',
    projectId: 'kipas-otomatis-7d7da',
    databaseURL: 'https://kipas-otomatis-7d7da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kipas-otomatis-7d7da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOoEN41HjHY-T0rqN5yJBQ7dfZqXyf2w',
    appId: '1:1081103792148:ios:2b81ca02d998c3b835cf01',
    messagingSenderId: '1081103792148',
    projectId: 'kipas-otomatis-7d7da',
    databaseURL: 'https://kipas-otomatis-7d7da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kipas-otomatis-7d7da.firebasestorage.app',
    iosBundleId: 'com.example.monitorSuhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOoEN41HjHY-T0rqN5yJBQ7dfZqXyf2w',
    appId: '1:1081103792148:ios:2b81ca02d998c3b835cf01',
    messagingSenderId: '1081103792148',
    projectId: 'kipas-otomatis-7d7da',
    databaseURL: 'https://kipas-otomatis-7d7da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kipas-otomatis-7d7da.firebasestorage.app',
    iosBundleId: 'com.example.monitorSuhu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQGZ_7NQCYlBOIyDsSnWqEqrkn2j0Ebv4',
    appId: '1:1081103792148:web:717e32a32720a0e035cf01',
    messagingSenderId: '1081103792148',
    projectId: 'kipas-otomatis-7d7da',
    authDomain: 'kipas-otomatis-7d7da.firebaseapp.com',
    databaseURL: 'https://kipas-otomatis-7d7da-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kipas-otomatis-7d7da.firebasestorage.app',
    measurementId: 'G-Y0SR3XE9QX',
  );
}
